# Generated by Django 5.0.2 on 2024-02-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_state', models.IntegerField(max_length=10)),
                ('name_state', models.CharField(max_length=200)),
                ('name_station', models.CharField(max_length=200)),
                ('id_wmo', models.IntegerField(max_length=10)),
                ('lat_num', models.FloatField(max_length=10)),
                ('lon_num', models.FloatField(max_length=10)),
                ('category_name', models.CharField(max_length=200)),
                ('category_id', models.IntegerField(max_length=10)),
                ('category_type', models.CharField(max_length=200)),
                ('name_city', models.CharField(max_length=200)),
            ],
        ),
    ]
