# Generated by Django 5.0.2 on 2024-02-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetDataSynop_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField()),
                ('period_visitor', models.CharField(max_length=100)),
                ('date_visit', models.DateTimeField()),
                ('period_thermometer', models.IntegerField()),
                ('period_screen_box', models.IntegerField()),
                ('period_rain_gauge', models.IntegerField()),
                ('period_rain_gauge_siphon', models.IntegerField()),
                ('period_sundial', models.IntegerField()),
                ('period_evaporation_pan', models.IntegerField()),
                ('period_sensors', models.IntegerField()),
                ('period_data_logger_panel', models.IntegerField()),
                ('period_infrastructure', models.IntegerField()),
                ('calibration_traditional_mercury_press_gauge', models.IntegerField()),
                ('calibration_traditional_wind_speed', models.IntegerField()),
                ('calibration_traditional_wind_direction', models.IntegerField()),
                ('calibration_traditional_digital_press_gauge', models.IntegerField()),
                ('calibration_traditional_radiation', models.IntegerField()),
                ('calibration_automatic_pressure', models.IntegerField()),
                ('calibration_automatic_tem_hum', models.IntegerField()),
                ('calibration_automatic_radiation', models.IntegerField()),
                ('seconder', models.CharField(max_length=100)),
                ('seconder_date', models.DateTimeField()),
            ],
        ),
    ]
