# Generated by Django 5.0.2 on 2024-02-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getInfo', '0002_getdatasynop_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='category_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='id_state',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='id_wmo',
            field=models.IntegerField(),
        ),
    ]
