# Generated by Django 5.0.2 on 2024-02-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getInfo', '0004_rename_getdatasynop_main_getdatasynop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GetDataSynop',
            new_name='GetDataSynop_main',
        ),
    ]
