# Generated by Django 5.0.2 on 2024-02-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getInfo', '0005_rename_getdatasynop_getdatasynop_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='date_visit',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
