# Generated by Django 5.0.2 on 2024-02-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getInfo', '0006_alter_getdatasynop_main_date_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='calibration_automatic_pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='calibration_automatic_radiation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='calibration_automatic_tem_hum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='calibration_traditional_digital_press_gauge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='calibration_traditional_mercury_press_gauge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='calibration_traditional_radiation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='calibration_traditional_wind_direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='calibration_traditional_wind_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='period_data_logger_panel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='period_evaporation_pan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='period_infrastructure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='period_rain_gauge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='period_rain_gauge_siphon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='period_screen_box',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='period_sensors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='period_sundial',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='period_thermometer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getdatasynop_main',
            name='seconder_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='lat_num',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='lon_num',
            field=models.FloatField(),
        ),
    ]
